version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  jobs:
    install:
      - pip install -r docs/requirements.txt
      - pip install -e .

    build:
      html:                           # ← builder name here
        - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html