name: Publish Wheels

# run this after your build workflow completes successfully
on:
  workflow_run:
    workflows: ["Build Wheels"]
    types: [ completed ]

jobs:
  publish:
    if: ${{
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_ref, 'v')
    }}
    runs-on: ubuntu-latest
    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse

      - name: Install Twine
        run: pip install --upgrade twine

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload wheelhouse/*.whl